### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F10-1

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F10-1/main#238]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [ ] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @e0313687 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-1/main/pull/225 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/223 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/217 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/206 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/200 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/191 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/128 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/225 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/223 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/217 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/206 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/200 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/191 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/138 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/128 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/124 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/92 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/44 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @namiwa for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-1/main/pull/227 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/226 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/219 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/215 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/198 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/227 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/226 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/219 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/215 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/198 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/183 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/179 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/138 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/124 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/92 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/74 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/43 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/37 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/4 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/3 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @kyawtsan99 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-1/main/pull/216 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/201 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/195 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/133 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/127 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/216 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/201 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/195 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/182 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/138 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/127 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/124 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/92 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @longlece for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-1/main/pull/224 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/220 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/214 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/207 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/205 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/203 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/130 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/125 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/224 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/220 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/218 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/214 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/213 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/207 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/205 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/203 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/138 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/137 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/130 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/125 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/124 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/105 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/92 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @andrewleow97 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F10-1/main/pull/192 https://github.com/AY1920S1-CS2113T-F10-1/main/pull/192 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/189 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/187 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/185 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/180 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/177 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/175 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/172 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/171 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/167 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/166 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/160 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/157 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/156 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/155 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/154 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/150 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/149 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/148 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/147 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/146 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/145 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/144 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/142 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/140 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/138 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/136 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/124 https://github.com/AY1920S1-CS2113T-F10-1/main/issues/92 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @jtankw3

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
